const data = [
  {
    url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    channel: "raunak.kumar.4",
    description: "ok working",
    song: "the gmae of thrones",
    likes: "111",
    messages: "222",
    shares: "333",
  },
  {
    url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    channel: "raunak.kumar.4",
    description: "ok working",
    song: "the gmae of thrones",
    likes: "111",
    messages: "222",
    shares: "333",
  },
  {
    url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    channel: "raunak.kumar.4",
    description: "ok working",
    song: "the gmae of thrones",
    likes: "111",
    messages: "222",
    shares: "333",
  },
  {
    url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    channel: "raunak.kumar.4",
    description: "ok working",
    song: "the gmae of thrones",
    likes: "111",
    messages: "222",
    shares: "333",
  },
  {
    url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    channel: "raunak.kumar.4",
    description: "ok working",
    song: "the gmae of thrones",
    likes: "111",
    messages: "222",
    shares: "333",
  },
  {
    url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    channel: "raunak.kumar.4",
    description: "ok working",
    song: "the gmae of thrones",
    likes: "111",
    messages: "222",
    shares: "333",
  },
];

export default data;
